import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrationsc1772986209399 implements MigrationInterface {
    name = 'Migrationsc1772986209399'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "roles_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "memberships_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "memberships_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "memberships_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "clients_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sms_messages" DROP CONSTRAINT "sms_messages_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sms_messages" DROP CONSTRAINT "sms_messages_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "user_profiles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "services_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "bookings_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "bookings_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "bookings_staff_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "bookings_service_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_knowledge_base_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "knowledge_bases" DROP CONSTRAINT "knowledge_bases_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "chunks" DROP CONSTRAINT "chunks_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "chunks" DROP CONSTRAINT "chunks_document_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "embeddings" DROP CONSTRAINT "embeddings_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "embeddings" DROP CONSTRAINT "embeddings_chunk_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "invites_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "invites_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "invites_invited_by_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "folders" DROP CONSTRAINT "folders_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "folders" DROP CONSTRAINT "folders_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "files_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "files_knowledge_base_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "files_uploaded_by_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "files_folder_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "chat_messages_session_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "chat_sessions_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "chat_sessions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "chat_sessions_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "staff_services" DROP CONSTRAINT "staff_services_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "staff_services" DROP CONSTRAINT "staff_services_service_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing_subscriptions" DROP CONSTRAINT "billing_subscriptions_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing_customers" DROP CONSTRAINT "billing_customers_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "password_reset_tokens_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "password_reset_tokens_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_org_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."roles_org_name_idx"`);
        await queryRunner.query(`DROP INDEX "public"."memberships_org_user_idx"`);
        await queryRunner.query(`DROP INDEX "public"."orgs_phone_idx"`);
        await queryRunner.query(`DROP INDEX "public"."clients_org_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."clients_org_email_idx"`);
        await queryRunner.query(`DROP INDEX "public"."clients_org_name_idx"`);
        await queryRunner.query(`DROP INDEX "public"."clients_org_phone_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sms_messages_org_direction_created_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sms_messages_org_created_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sms_messages_client_idx"`);
        await queryRunner.query(`DROP INDEX "public"."services_org_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."services_org_active_idx"`);
        await queryRunner.query(`DROP INDEX "public"."bookings_org_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."bookings_staff_start_idx"`);
        await queryRunner.query(`DROP INDEX "public"."bookings_org_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."bookings_org_date_idx"`);
        await queryRunner.query(`DROP INDEX "public"."documents_org_kb_idx"`);
        await queryRunner.query(`DROP INDEX "public"."knowledge_bases_org_name_idx"`);
        await queryRunner.query(`DROP INDEX "public"."chunks_document_idx"`);
        await queryRunner.query(`DROP INDEX "public"."chunks_org_idx"`);
        await queryRunner.query(`DROP INDEX "public"."embeddings_org_idx"`);
        await queryRunner.query(`DROP INDEX "public"."embeddings_vector_idx"`);
        await queryRunner.query(`DROP INDEX "public"."invites_org_email_idx"`);
        await queryRunner.query(`DROP INDEX "public"."invites_token_idx"`);
        await queryRunner.query(`DROP INDEX "public"."folders_org_parent_idx"`);
        await queryRunner.query(`DROP INDEX "public"."files_org_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."files_org_kb_idx"`);
        await queryRunner.query(`DROP INDEX "public"."files_storage_key_idx"`);
        await queryRunner.query(`DROP INDEX "public"."files_folder_idx"`);
        await queryRunner.query(`DROP INDEX "public"."chat_messages_session_created_idx"`);
        await queryRunner.query(`DROP INDEX "public"."chat_sessions_org_user_updated_idx"`);
        await queryRunner.query(`DROP INDEX "public"."chat_sessions_org_source_updated_idx"`);
        await queryRunner.query(`DROP INDEX "public"."chat_sessions_sms_thread_unique_idx"`);
        await queryRunner.query(`DROP INDEX "public"."staff_services_user_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."staff_services_service_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."billing_subscriptions_customer_idx"`);
        await queryRunner.query(`DROP INDEX "public"."billing_subscriptions_subscription_idx"`);
        await queryRunner.query(`DROP INDEX "public"."billing_subscriptions_status_trial_idx"`);
        await queryRunner.query(`DROP INDEX "public"."password_reset_tokens_hash_idx"`);
        await queryRunner.query(`DROP INDEX "public"."password_reset_tokens_org_user_expires_idx"`);
        await queryRunner.query(`DROP INDEX "public"."refresh_tokens_hash_idx"`);
        await queryRunner.query(`DROP INDEX "public"."refresh_tokens_user_org_idx"`);
        await queryRunner.query(`ALTER TABLE "sms_messages" DROP CONSTRAINT "sms_messages_direction_check"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "chat_sessions_source_check"`);
        await queryRunner.query(`ALTER TABLE "staff_services" DROP CONSTRAINT "staff_services_user_id_service_id_key"`);
        await queryRunner.query(`CREATE TABLE "sms_retention_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "org_id" uuid NOT NULL, "is_enabled" boolean NOT NULL DEFAULT true, "we_miss_you_enabled" boolean NOT NULL DEFAULT true, "next_booking_special_enabled" boolean NOT NULL DEFAULT true, "churn_days" integer NOT NULL DEFAULT '30', "last_run_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3863db9fb924717f4a56dccacd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b93e238c6ccba1b26564f63a3e" ON "sms_retention_settings" ("org_id") `);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "org_id" uuid NOT NULL, "user_id" uuid, "endpoint" text NOT NULL, "p256dh" text NOT NULL, "auth" text NOT NULL, "expiration_time" bigint, "user_agent" text, CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7b28928b80442a7700d06dd16" ON "push_subscriptions" ("org_id", "endpoint") `);
        await queryRunner.query(`CREATE INDEX "IDX_45629ccc6af191f95f8593c556" ON "push_subscriptions" ("org_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_753595cb83a1a2c1f1eeed503e" ON "push_subscriptions" ("org_id") `);
        await queryRunner.query(`CREATE TABLE "notification_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "org_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "channel" text NOT NULL, "status" text NOT NULL DEFAULT 'pending', "payload" jsonb NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_81daeff81f237bd384f7cfc4a4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a3cbf2107d032871dac8ecacff" ON "notification_deliveries" ("org_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_c98e6518f68744cb8e28e2681e" ON "notification_deliveries" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0d18179a540c04363a0347760" ON "notification_deliveries" ("org_id", "status") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "org_id" uuid NOT NULL, "user_id" uuid NOT NULL, "booking_id" uuid, "type" text NOT NULL, "title" text NOT NULL, "message" text NOT NULL, "data" jsonb, "read_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5d0accbc36de15323c983bf726" ON "notifications" ("org_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f98e969fe407e976e147efde22" ON "notifications" ("org_id", "user_id") `);
        await queryRunner.query(`ALTER TABLE "orgs" ADD "country" text NOT NULL DEFAULT 'US'`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "source" text NOT NULL DEFAULT 'dashboard'`);
        await queryRunner.query(`ALTER TABLE "orgs" ALTER COLUMN "working_hours_start" SET DEFAULT '09:00'`);
        await queryRunner.query(`ALTER TABLE "orgs" ALTER COLUMN "working_hours_end" SET DEFAULT '20:00'`);
        await queryRunner.query(`ALTER TABLE "sms_messages" DROP CONSTRAINT "sms_messages_message_sid_key"`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "color" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "embeddings" DROP COLUMN "vector"`);
        await queryRunner.query(`ALTER TABLE "embeddings" ADD "vector" vector NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invites" ALTER COLUMN "invited_by_id" SET NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b5a4b189b5d2f19bd67ad48101" ON "roles" ("org_id", "name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8a43e03ebb7e6f6486a1eab939" ON "memberships" ("org_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_07bd58978f0db3904d9374a176" ON "clients" ("org_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ea2dcfa3602af29381778de4e" ON "clients" ("org_id", "email") `);
        await queryRunner.query(`CREATE INDEX "IDX_015dc4e5498f6340e5dcc2f524" ON "clients" ("org_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8e7a7273b4e85283215814b5a4" ON "sms_messages" ("message_sid") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8cbba4021d7de6e3fd96bc3aa" ON "sms_messages" ("org_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6ca9503d77ae39b4b5a6cc3ba8" ON "user_profiles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9c811ed3a31fd73376c3e4663" ON "services" ("org_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_1cde87d283c408140fc80a1305" ON "services" ("org_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c40f5be88d6b6401a66a87f00c" ON "bookings" ("org_id", "start_time", "end_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_695aa25f26408df853597d89d1" ON "bookings" ("org_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c9111ebed325e781c7f5de87f" ON "bookings" ("staff_id", "start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_485e8b0f78bc94bbca9fb7fd16" ON "bookings" ("org_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e7723f609075377e7bd437ebe" ON "documents" ("org_id", "knowledge_base_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3bbc10f166ac228390a7d92144" ON "knowledge_bases" ("org_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_08b9ab1dfb5c84dbb65247a469" ON "chunks" ("org_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_433a7c08a1e2d920684f1884f6" ON "chunks" ("document_id", "idx") `);
        await queryRunner.query(`CREATE INDEX "IDX_18036af03dfe415f1f9b586ec1" ON "embeddings" ("org_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_18a9a6c85f7cc6f42ebef3b318" ON "invites" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_843f0efb67d82c629b8e42fcf6" ON "invites" ("org_id", "email") `);
        await queryRunner.query(`CREATE INDEX "IDX_568f0bb01301fb8a043bd39fbe" ON "folders" ("org_id", "parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_27bc84e6954d2fa309a4f61326" ON "files" ("folder_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e916afbf2015d561fd0842ff89" ON "files" ("storage_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_320934535c1e976c91c044fde2" ON "files" ("org_id", "knowledge_base_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aeab8351dcb5f888319a40e087" ON "files" ("org_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_34bfc66e62161622b54ac9af4a" ON "chat_messages" ("session_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fea581f6f7f9f9a12c5f3ff40b" ON "chat_sessions" ("org_id", "source", "external_thread_key") WHERE "source" = 'sms' AND "external_thread_key" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_58c66cde7d48dd9d53fbc57dc2" ON "chat_sessions" ("org_id", "source", "updated_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_1848c9373709eb30ad12e97bbb" ON "chat_sessions" ("org_id", "user_id", "updated_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb9700763bdcd25dd53d264a6b" ON "billing_subscriptions" ("status", "trial_end") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba577fd74443075324874aa1a0" ON "billing_subscriptions" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4fe3d98619813c9f254fd1108" ON "billing_subscriptions" ("customer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8b88541a524ba0a6440b2b3090" ON "billing_subscriptions" ("org_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_12739d287fe1ee4982a657facd" ON "password_reset_tokens" ("org_id", "user_id", "expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_91185d86d5d7557b19abbb2868" ON "password_reset_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_83ccee503cedad6c73f4e96a23" ON "refresh_tokens" ("user_id", "org_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7838d2ba25be1342091b6695f" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "UQ_25d24010f53bb80b78e412c9656" UNIQUE ("role_id", "permission_id")`);
        await queryRunner.query(`ALTER TABLE "staff_services" ADD CONSTRAINT "UQ_a1a1d3e3e6c160aaca3c23e2939" UNIQUE ("user_id", "service_id")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_ba4f96af4628cc8b18e940436d8" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_8c6a511c72951c42e008f5537dc" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_7c1e2fdfed4f6838e0c05ae5051" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_2fb8d236390c9977525fc4596ad" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sms_retention_settings" ADD CONSTRAINT "FK_b93e238c6ccba1b26564f63a3e0" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_015dc4e5498f6340e5dcc2f524a" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sms_messages" ADD CONSTRAINT "FK_387fc97bad21e4750f2af1c6ffa" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sms_messages" ADD CONSTRAINT "FK_12d317f06ce518f4b34675b6728" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_753595cb83a1a2c1f1eeed503ef" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_6771f119f1c06d2ccf38f238664" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_1cde87d283c408140fc80a13051" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_485e8b0f78bc94bbca9fb7fd163" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_23096dca2f7a9d1505d0267d4c6" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_016e3ee9c10ae3cc8ecb3765c4d" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_df22e2beaabc33a432b4f65e3c2" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "FK_260a3687df5e2eba51bd3230768" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "FK_c98e6518f68744cb8e28e2681e4" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_324de082662023de80fdf068978" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_3f5c2196c2b2af99a4697e51741" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_74ab69a4f52faa3b422264b6c83" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_bases" ADD CONSTRAINT "FK_ff55dd7d1125b82e4bf31ef93c9" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chunks" ADD CONSTRAINT "FK_d841de45a719fe1f35213d79207" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embeddings" ADD CONSTRAINT "FK_84ee81f57b2d0df18fec67ae4c4" FOREIGN KEY ("chunk_id") REFERENCES "chunks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_b41b0d83a220ef17786967f4d61" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_8b432fcafe8246529b0476feb59" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_997b4c1cbb58bd9467ab0f8e0e3" FOREIGN KEY ("invited_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folders" ADD CONSTRAINT "FK_9c5b5ead06178ad73eb13831152" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folders" ADD CONSTRAINT "FK_938a930768697b6ece215667d8e" FOREIGN KEY ("parent_id") REFERENCES "folders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_6dcf2eb04af438e419ca47fb8b9" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_ea8be5a6fb18c83506e07a992e1" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_27bc84e6954d2fa309a4f61326f" FOREIGN KEY ("folder_id") REFERENCES "folders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_b25b4b9c85b6e6ffa2789dc5da5" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_0672782561e44d43febcfba2984" FOREIGN KEY ("session_id") REFERENCES "chat_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_44bad67d6622740f87298d2ba2d" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_1fa209cf48ae975a109366542a5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_77f3f009254854684334e1ec309" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_services" ADD CONSTRAINT "FK_807b0f434948cd9f12f2b21e890" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_services" ADD CONSTRAINT "FK_9c320b3170bb98885902ff9ef85" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_subscriptions" ADD CONSTRAINT "FK_8b88541a524ba0a6440b2b30902" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_customers" ADD CONSTRAINT "FK_41d007c86aea054efc557590632" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_b4a761c5ddc363e9ef5ba4499d0" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_346eb0e86f14437f18bf3f4fe8f" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_346eb0e86f14437f18bf3f4fe8f"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_b4a761c5ddc363e9ef5ba4499d0"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c"`);
        await queryRunner.query(`ALTER TABLE "billing_customers" DROP CONSTRAINT "FK_41d007c86aea054efc557590632"`);
        await queryRunner.query(`ALTER TABLE "billing_subscriptions" DROP CONSTRAINT "FK_8b88541a524ba0a6440b2b30902"`);
        await queryRunner.query(`ALTER TABLE "staff_services" DROP CONSTRAINT "FK_9c320b3170bb98885902ff9ef85"`);
        await queryRunner.query(`ALTER TABLE "staff_services" DROP CONSTRAINT "FK_807b0f434948cd9f12f2b21e890"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_77f3f009254854684334e1ec309"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_1fa209cf48ae975a109366542a5"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_44bad67d6622740f87298d2ba2d"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_0672782561e44d43febcfba2984"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_b25b4b9c85b6e6ffa2789dc5da5"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_27bc84e6954d2fa309a4f61326f"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_ea8be5a6fb18c83506e07a992e1"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_6dcf2eb04af438e419ca47fb8b9"`);
        await queryRunner.query(`ALTER TABLE "folders" DROP CONSTRAINT "FK_938a930768697b6ece215667d8e"`);
        await queryRunner.query(`ALTER TABLE "folders" DROP CONSTRAINT "FK_9c5b5ead06178ad73eb13831152"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_997b4c1cbb58bd9467ab0f8e0e3"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_8b432fcafe8246529b0476feb59"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_b41b0d83a220ef17786967f4d61"`);
        await queryRunner.query(`ALTER TABLE "embeddings" DROP CONSTRAINT "FK_84ee81f57b2d0df18fec67ae4c4"`);
        await queryRunner.query(`ALTER TABLE "chunks" DROP CONSTRAINT "FK_d841de45a719fe1f35213d79207"`);
        await queryRunner.query(`ALTER TABLE "knowledge_bases" DROP CONSTRAINT "FK_ff55dd7d1125b82e4bf31ef93c9"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_74ab69a4f52faa3b422264b6c83"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_3f5c2196c2b2af99a4697e51741"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_324de082662023de80fdf068978"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "FK_c98e6518f68744cb8e28e2681e4"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "FK_260a3687df5e2eba51bd3230768"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_df22e2beaabc33a432b4f65e3c2"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_016e3ee9c10ae3cc8ecb3765c4d"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_23096dca2f7a9d1505d0267d4c6"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_485e8b0f78bc94bbca9fb7fd163"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_1cde87d283c408140fc80a13051"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_6771f119f1c06d2ccf38f238664"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_753595cb83a1a2c1f1eeed503ef"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88"`);
        await queryRunner.query(`ALTER TABLE "sms_messages" DROP CONSTRAINT "FK_12d317f06ce518f4b34675b6728"`);
        await queryRunner.query(`ALTER TABLE "sms_messages" DROP CONSTRAINT "FK_387fc97bad21e4750f2af1c6ffa"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_015dc4e5498f6340e5dcc2f524a"`);
        await queryRunner.query(`ALTER TABLE "sms_retention_settings" DROP CONSTRAINT "FK_b93e238c6ccba1b26564f63a3e0"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_2fb8d236390c9977525fc4596ad"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_7c1e2fdfed4f6838e0c05ae5051"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_8c6a511c72951c42e008f5537dc"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_ba4f96af4628cc8b18e940436d8"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "staff_services" DROP CONSTRAINT "UQ_a1a1d3e3e6c160aaca3c23e2939"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "UQ_25d24010f53bb80b78e412c9656"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7838d2ba25be1342091b6695f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83ccee503cedad6c73f4e96a23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91185d86d5d7557b19abbb2868"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12739d287fe1ee4982a657facd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b88541a524ba0a6440b2b3090"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4fe3d98619813c9f254fd1108"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba577fd74443075324874aa1a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb9700763bdcd25dd53d264a6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1848c9373709eb30ad12e97bbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58c66cde7d48dd9d53fbc57dc2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fea581f6f7f9f9a12c5f3ff40b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34bfc66e62161622b54ac9af4a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aeab8351dcb5f888319a40e087"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_320934535c1e976c91c044fde2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e916afbf2015d561fd0842ff89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27bc84e6954d2fa309a4f61326"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_568f0bb01301fb8a043bd39fbe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_843f0efb67d82c629b8e42fcf6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18a9a6c85f7cc6f42ebef3b318"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18036af03dfe415f1f9b586ec1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_433a7c08a1e2d920684f1884f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08b9ab1dfb5c84dbb65247a469"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bbc10f166ac228390a7d92144"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e7723f609075377e7bd437ebe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_485e8b0f78bc94bbca9fb7fd16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c9111ebed325e781c7f5de87f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_695aa25f26408df853597d89d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c40f5be88d6b6401a66a87f00c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cde87d283c408140fc80a1305"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9c811ed3a31fd73376c3e4663"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ca9503d77ae39b4b5a6cc3ba8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8cbba4021d7de6e3fd96bc3aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e7a7273b4e85283215814b5a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_015dc4e5498f6340e5dcc2f524"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ea2dcfa3602af29381778de4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07bd58978f0db3904d9374a176"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a43e03ebb7e6f6486a1eab939"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5a4b189b5d2f19bd67ad48101"`);
        await queryRunner.query(`ALTER TABLE "invites" ALTER COLUMN "invited_by_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "embeddings" DROP COLUMN "vector"`);
        await queryRunner.query(`ALTER TABLE "embeddings" ADD "vector" vector(1536) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "color" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sms_messages" ADD CONSTRAINT "sms_messages_message_sid_key" UNIQUE ("message_sid")`);
        await queryRunner.query(`ALTER TABLE "orgs" ALTER COLUMN "working_hours_end" SET DEFAULT '20:00:00'`);
        await queryRunner.query(`ALTER TABLE "orgs" ALTER COLUMN "working_hours_start" SET DEFAULT '09:00:00'`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "orgs" DROP COLUMN "country"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f98e969fe407e976e147efde22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d0accbc36de15323c983bf726"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0d18179a540c04363a0347760"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c98e6518f68744cb8e28e2681e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3cbf2107d032871dac8ecacff"`);
        await queryRunner.query(`DROP TABLE "notification_deliveries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_753595cb83a1a2c1f1eeed503e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45629ccc6af191f95f8593c556"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7b28928b80442a7700d06dd16"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b93e238c6ccba1b26564f63a3e"`);
        await queryRunner.query(`DROP TABLE "sms_retention_settings"`);
        await queryRunner.query(`ALTER TABLE "staff_services" ADD CONSTRAINT "staff_services_user_id_service_id_key" UNIQUE ("user_id", "service_id")`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "chat_sessions_source_check" CHECK ((source = ANY (ARRAY['web'::text, 'sms'::text])))`);
        await queryRunner.query(`ALTER TABLE "sms_messages" ADD CONSTRAINT "sms_messages_direction_check" CHECK ((direction = ANY (ARRAY['inbound'::text, 'outbound'::text])))`);
        await queryRunner.query(`CREATE INDEX "refresh_tokens_user_org_idx" ON "refresh_tokens" ("user_id", "org_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "refresh_tokens_hash_idx" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "password_reset_tokens_org_user_expires_idx" ON "password_reset_tokens" ("org_id", "user_id", "expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "password_reset_tokens_hash_idx" ON "password_reset_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "billing_subscriptions_status_trial_idx" ON "billing_subscriptions" ("status", "trial_end") `);
        await queryRunner.query(`CREATE INDEX "billing_subscriptions_subscription_idx" ON "billing_subscriptions" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "billing_subscriptions_customer_idx" ON "billing_subscriptions" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "staff_services_service_id_idx" ON "staff_services" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "staff_services_user_id_idx" ON "staff_services" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "chat_sessions_sms_thread_unique_idx" ON "chat_sessions" ("org_id", "source", "external_thread_key") WHERE ((source = 'sms'::text) AND (external_thread_key IS NOT NULL))`);
        await queryRunner.query(`CREATE INDEX "chat_sessions_org_source_updated_idx" ON "chat_sessions" ("org_id", "updated_at", "source") `);
        await queryRunner.query(`CREATE INDEX "chat_sessions_org_user_updated_idx" ON "chat_sessions" ("org_id", "user_id", "updated_at") `);
        await queryRunner.query(`CREATE INDEX "chat_messages_session_created_idx" ON "chat_messages" ("session_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "files_folder_idx" ON "files" ("folder_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "files_storage_key_idx" ON "files" ("storage_key") `);
        await queryRunner.query(`CREATE INDEX "files_org_kb_idx" ON "files" ("org_id", "knowledge_base_id") `);
        await queryRunner.query(`CREATE INDEX "files_org_status_idx" ON "files" ("org_id", "status") `);
        await queryRunner.query(`CREATE INDEX "folders_org_parent_idx" ON "folders" ("org_id", "parent_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "invites_token_idx" ON "invites" ("token") `);
        await queryRunner.query(`CREATE INDEX "invites_org_email_idx" ON "invites" ("org_id", "email") `);
        await queryRunner.query(`CREATE INDEX "embeddings_vector_idx" ON "embeddings" ("vector") `);
        await queryRunner.query(`CREATE INDEX "embeddings_org_idx" ON "embeddings" ("org_id") `);
        await queryRunner.query(`CREATE INDEX "chunks_org_idx" ON "chunks" ("org_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "chunks_document_idx" ON "chunks" ("document_id", "idx") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "knowledge_bases_org_name_idx" ON "knowledge_bases" ("org_id", "name") `);
        await queryRunner.query(`CREATE INDEX "documents_org_kb_idx" ON "documents" ("org_id", "knowledge_base_id") `);
        await queryRunner.query(`CREATE INDEX "bookings_org_date_idx" ON "bookings" ("org_id", "start_time", "end_time") `);
        await queryRunner.query(`CREATE INDEX "bookings_org_status_idx" ON "bookings" ("org_id", "status") `);
        await queryRunner.query(`CREATE INDEX "bookings_staff_start_idx" ON "bookings" ("staff_id", "start_time") `);
        await queryRunner.query(`CREATE INDEX "bookings_org_id_idx" ON "bookings" ("org_id") `);
        await queryRunner.query(`CREATE INDEX "services_org_active_idx" ON "services" ("org_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "services_org_id_idx" ON "services" ("org_id") `);
        await queryRunner.query(`CREATE INDEX "sms_messages_client_idx" ON "sms_messages" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "sms_messages_org_created_idx" ON "sms_messages" ("org_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "sms_messages_org_direction_created_idx" ON "sms_messages" ("org_id", "created_at", "direction") `);
        await queryRunner.query(`CREATE INDEX "clients_org_phone_idx" ON "clients" ("org_id", "phone") WHERE (phone IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "clients_org_name_idx" ON "clients" ("org_id", "name") `);
        await queryRunner.query(`CREATE INDEX "clients_org_email_idx" ON "clients" ("org_id", "email") `);
        await queryRunner.query(`CREATE INDEX "clients_org_id_idx" ON "clients" ("org_id") `);
        await queryRunner.query(`CREATE INDEX "orgs_phone_idx" ON "orgs" ("phone") WHERE (phone IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "memberships_org_user_idx" ON "memberships" ("org_id", "user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "roles_org_name_idx" ON "roles" ("org_id", "name") `);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_customers" ADD CONSTRAINT "billing_customers_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_services" ADD CONSTRAINT "staff_services_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_services" ADD CONSTRAINT "staff_services_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "chat_sessions_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "chat_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "chat_sessions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "chat_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "files_folder_id_fkey" FOREIGN KEY ("folder_id") REFERENCES "folders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "files_uploaded_by_id_fkey" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "files_knowledge_base_id_fkey" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "files_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folders" ADD CONSTRAINT "folders_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "folders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folders" ADD CONSTRAINT "folders_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "invites_invited_by_id_fkey" FOREIGN KEY ("invited_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "invites_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "invites_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embeddings" ADD CONSTRAINT "embeddings_chunk_id_fkey" FOREIGN KEY ("chunk_id") REFERENCES "chunks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embeddings" ADD CONSTRAINT "embeddings_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chunks" ADD CONSTRAINT "chunks_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chunks" ADD CONSTRAINT "chunks_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_bases" ADD CONSTRAINT "knowledge_bases_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_knowledge_base_id_fkey" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "bookings_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "bookings_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "bookings_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "bookings_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "services_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "user_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sms_messages" ADD CONSTRAINT "sms_messages_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sms_messages" ADD CONSTRAINT "sms_messages_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "clients_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "memberships_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "memberships_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "roles_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
